import queue
q = queue.Queue(5)
q.put(10)
q.put(20)
q.put(30)
q.put(40)
q.put(50)
print(q.queue)
print(q.qsize())
print(q.empty())
print(q.full())
data_q = q.get()
print(data_q)
print(q.qsize())
print(q.empty())
print(q.full())